### ISSUE TITLE
Responsive not supported?

### ISSUE THREAD

**Issue by ina6ra** [Jenesius/vue-modal#1]
Thank you for the wonderful library 😄
It is helpful because there was no modal library that can be used properly with Vue3.

It doesn't seem to be responsive, but I solved it by adding the following CSS.

```
.widget__modal-container__item-back {
  position: absolute;
}

.widget__modal-container__item {
  display: flex;
  align-items: center;
  justify-content: center;
}
```

**Comment by Jenesius** [comment]
Hello, @ina6ra.
You are welcome!
Yes - you're absolutely right, in my code was error,
![image](https://user-images.githubusercontent.com/21982550/127772645-e5098161-c4ec-4ca0-8fe3-bc90e7b71aa5.png)
I will change css styles and put this changes in 1.0.3 version.
Thnx!

**Comment by ina6ra** [comment]
Thanks @Jenesius 
I confirmed that it was supported in version 1.0.6
