### ISSUE TITLE
Vue Warn deprecation TRANSITION_GROUP_ROOT

### ISSUE THREAD

**Issue by rmp1985** [Jenesius/vue-modal#105]
Jenesius,

As I told you, I'm migrating and using Vue Compat.

It seems to me to be some warn regarding the library that is not adding a tag="span" for example for TransitionGroup (at <TransitionGroup name="modal-list" >). This solution seems to be simple too but I don't see any urgency.

![image](https://github.com/Jenesius/vue-modal/assets/52454226/9ae21544-0d31-43c4-8492-c3a91ab4551d)

**Comment by Jenesius** [comment]
I think that this problem will also disappear when the library structure is changed. I think it's time for me to tidy up all the code, simplify the documentation and update the version to 2.0.0

**Comment by Jenesius** [comment]
Hmm.

Tomorrow I will test the solution to this problem by simply adding tag. I didn't expect this to be a popular issue.

**Comment by rmp1985** [comment]
Cool, thank you very much and I look forward to it! I'm still migrating my vue 2 app to vue 3.

**Comment by Jenesius** [comment]
@rmp1985, Hello! Can you update to version 1.11.1. I added the required tag to transition-group

**Comment by rmp1985** [comment]
apologies for the delay! issue resolved thank you very much!
