### ISSUE TITLE
[BUG] На сайте кнопка Следующая страница всегда ведет на первую

### ISSUE THREAD

**Issue by Ada-lave** [Jenesius/vue-modal#108]
**Describe the bug**

**Please complete the following information:**

**Additional context**

**Comment by Jenesius** [comment]
I mean this is a problem in vitepress, I'll update to the latest version and check if it's fixed there

**Comment by Jenesius** [comment]
I thought the problem was with vitepress itself. It turned out that the link settings there are a little specific. I fixed this in the latest update.
