### ISSUE TITLE
modal cannot open when give namespace

### ISSUE THREAD

**Issue by drdevelop** [Jenesius/vue-modal#110]
example:
ModalA.vue:
```
<template>
hello A
</template>
```
openModal(ModalA, {}, { namespace: 'test' })

**Comment by drdevelop** [comment]
need Initial，but i think is a bit troublesome.

**Comment by drdevelop** [comment]
or can give a tip?

**Comment by rmp1985** [comment]
Please help me. This isn't working:
const instanceModal = await pushModal(modalComponent, props, { namespace: "notification" })

But this works:
const instanceModal = await pushModal(modalComponent, props)

Where am I going wrong? 

I would like to add a namespace so I can later specifically close it with popModal
