### ISSUE TITLE
click on the title, hold and drag

### ISSUE THREAD

**Issue by rmp1985** [Jenesius/vue-modal#114]
In our old vue2 dialog we had an interesting feature which was to click on the title of the dialog, hold and drag it to move on the screen. Would it be complicated to implement?

**Comment by Jenesius** [comment]
Hello. Interesting idea! I think this would be a cool feature of this library. Maybe I’ll make a prototype by the weekend, I need to think about how to allow dragging (I’ll see how it was done in Vue 2, if you have examples, I’ll be glad).
I think I can handle it in a couple of days.
A little experiment on binding `pointermove` and changing the window position:
![Clipchamp7-ezgif com-video-to-gif-converter](https://github.com/Jenesius/vue-modal/assets/21982550/f2bc6b53-4ef7-4c1b-88f1-7b85417b545c)

**Comment by rmp1985** [comment]
Cool! If it helps with the above we use:

"vue-js-modal": "2.0.1", 

and had this feature.

https://github.com/euvl/vue-js-modal

https://euvl.github.io/vue-js-modal/Properties.html#properties-2

It would be a draggable option

**Comment by rmp1985** [comment]
Hello Jenesius, how are you?

Have you taken a look at the possibility?

**Comment by Jenesius** [comment]
Hello, I forgot about this task a little...
In version `1.11.2` the **`draggable`** parameter was added, which accepts either a Boolean or a string value.
Move by clicking anywhere in the window:
```ts
openModal(ModalInfo, {info: "test", {
  draggable: true
}})
```
Draggable using css class:
```ts
openModal(ModalInfo, {info: "test", {
  draggable: '.modal-header'
}})
```
Draggable using css ID:
```ts
openModal(ModalInfo, {info: "test", {
  draggable: '#modal-header'
}})
```

**Comment by Jenesius** [comment]
I assume that I will have to make more changes, but this concept will not change anymore, so it can be safely used. You can also pass draggable in 'config', which will be installed by default for everyone.

**Comment by rmp1985** [comment]
Thank you very much! Tomorrow I'll be able to do a test and give you feedback.

But 99% of my case is with pushModal and not openModal, will it work? I believe this configuration in config is much better in my case.

**Comment by Jenesius** [comment]
Thank you!
Absolutely, pushModal and openModal are identical in terms of use. If you look inside, openModal uses pushModal to open a modal window. So the next code also will work:
```ts
pushModal(ModalInfo, {info: "test"}, {
  draggable: '#modal-header'
})
```

**Comment by rmp1985** [comment]
Jenesius, I don't know where I'm going wrong but this call correctly opens a dialog, I just added the draggable but it just doesn't work... updated to 1.11.2

await pushModal(modalComponent, propsRepassar, { draggable: true })

**Comment by Jenesius** [comment]
@rmp1985, Please tell me which browser and which version you are using? For this feature I use addEventListener('pointerdown') and it has full browser support. And after trying to move the modal window, does it close? You can also see if the transfrom properties are added to css (as in the picture)

![image](https://github.com/Jenesius/vue-modal/assets/21982550/01c3124a-ebe1-4cc8-9cd5-a99847cbec2b)

**Comment by rmp1985** [comment]
I'm using Google Chrome Version 124.0.6367.208 (Official version) 64 bits

But maybe I'm doing something wrong... but the transform really isn't showing up

When I click on the dialog nothing happens (it doesn't close) it's as if draggable had no effect.

**Comment by rmp1985** [comment]
![image](https://github.com/Jenesius/vue-modal/assets/52454226/60d81998-06e9-4992-a693-b7c3f7143924)


![image](https://github.com/Jenesius/vue-modal/assets/52454226/5031d1b4-caf7-4686-bd45-26c4b67cd4bc)

**Comment by Jenesius** [comment]
Please show me what the html structure looks like a little higher, above the `span`. I see that you have two nested spans and then a div/div.

**Comment by rmp1985** [comment]
Jenesius, thank you for your patience.

Follow my html

I had to attach it in a zip

[div.zip](https://github.com/Jenesius/vue-modal/files/15416857/div.zip)

**Comment by Jenesius** [comment]
Thnx, i will check this zip today!

**Comment by Jenesius** [comment]
I just pasted the html into the component:
![image](https://github.com/Jenesius/vue-modal/assets/21982550/9e753553-1b33-4786-963f-552f2b953d32)
But there is one thing: as you can see in the picture, transform is set to the first element inside the container. Do you experience the same behavior again or not?

**Comment by Jenesius** [comment]
Let's continue. Transform is not set upon initialization. It appears when the block is moved. As I understand it, even after trying to drag and drop, nothing works.
I'll add debug in the new version, let's try to figure out exactly where it doesn't work.

**Comment by rmp1985** [comment]
ok thank you very much, I'm waiting for the version

**Comment by rmp1985** [comment]
![image](https://github.com/Jenesius/vue-modal/assets/52454226/3398544e-2dae-4da1-99c3-abf8a09b8a7c)

![image](https://github.com/Jenesius/vue-modal/assets/52454226/e18302c1-7aa6-487b-9da7-c6cb9a42090c)


Jenesius, does this help or do you need any more information?

**Comment by Jenesius** [comment]
Hmm, did I understand correctly that even when passing true, it writes that *draggable item not found*?

**Comment by rmp1985** [comment]
That's right! Sending true, or a class the result is the same.

**Comment by Jenesius** [comment]
Can you update to **1.11.4**.
Now logs will contains the selector. Also I add setTimeout, maybe it will resolve the problem...
And try send me logs from console again.

**Comment by rmp1985** [comment]
Track results with class .app-dialog

![image](https://github.com/Jenesius/vue-modal/assets/52454226/ef9c53fd-ea54-4336-bd05-2c3f46fabd2f)

Track results with true

![image](https://github.com/Jenesius/vue-modal/assets/52454226/e856a8da-521f-46ee-9868-306a7f77a490)

![image](https://github.com/Jenesius/vue-modal/assets/52454226/80796fee-f2b8-4319-83ec-bb0a56dc6ccd)

**Comment by Jenesius** [comment]
In the future *modalid* will have a normal form, let's leave it like that for now)
This looks very intriguing. 
If you run document.querySelector('[modalid=_ modal _0]') in the console, will the result show html or not (Example on the screenshot)?
![image](https://github.com/Jenesius/vue-modal/assets/21982550/e8efed5f-f4e7-42c1-b9f0-e85837e50666)
At the moment I have two guesses:
1. Perhaps v-if is present on the modal window, which is why it does not appear immediately but with a delay. Because of this, at the time of initialization the html block does not yet exist.
2. The modal component has several root nodes and because of this **modalid** does not work. Although you have all the parameters displayed in the screenshot. So this point disappears.

Inside the library it looks like this:
```ts
const draggableSelector = typeof modal.draggable === 'string' ? modal.draggable : `[modalid=_modal_${props.id}]`
debug(`The modal window is movable(${draggableSelector}).`)	
addDraggable(document.querySelector(draggableSelector))
```
We need to understand why `document.querySelector(draggable Selector)` returns `null`

**Comment by Jenesius** [comment]
hmm, this all looks wrong. I'm working now and will post a new version covered with tests.

**Comment by Jenesius** [comment]
Try updating to version **1.11.5**.
And repeat the experience.

**Comment by rmp1985** [comment]
let's go!

I analyzed my code and removed all v-ifs;

I tested with true and with class but unfortunately without a positive result yet;

![image](https://github.com/Jenesius/vue-modal/assets/52454226/c064e555-e6d3-4b66-ad43-f62fc055ef36)

**Comment by Jenesius** [comment]
This may not solve the problem, but we will understand what the problem may be. Update to **1.11.6**.

Also try running this code:
```ts
await pushModal(.......);
document.querySelector(`[modalid=_modal_0]`);
```
If that doesn't work, then this one will. This way we will understand at what point the window becomes available in your code. You can play with the timeout value:
```ts
const timeout = 50;
let attemp = 0;
await pushModal(.......);

fn();
functon fn() {
  const elModal = document.querySelector(`[modalid=_modal_0]`);
  if (!elModal) {
    console.log(`Attemp ${attemp} failed.`);
    attemp++;
    setTimeout(fn, timeout);
  } else console.log('Modal founded`);
}
```

**Comment by rmp1985** [comment]
Result:

At first opening around 5ms and then around 1ms...

![image](https://github.com/Jenesius/vue-modal/assets/52454226/a621a25a-625d-4756-b7b6-83488d862067)

But the library never finds...
![image](https://github.com/Jenesius/vue-modal/assets/52454226/9cedd0f9-28c3-4287-96c5-f4cf5ede8edc)

QuerySelect always finds
![image](https://github.com/Jenesius/vue-modal/assets/52454226/4981aa46-d7b3-4fc6-bd31-22a3000b2912)

**Comment by Jenesius** [comment]
Can you show the `modalComponent`, how its look inside.

**Comment by rmp1985** [comment]
Jenesius I thank you for now. But I'm returning to version 1.11.1 because I need to go to production. I saw that in addition to not working, this new draggrable parameter had a detrimental effect on the mobile version. As it is something simple but needs to be very well tested, I thought it was risky to put something like this up at the moment.
