### ISSUE TITLE
Add appear prop on transition-group for correct animation for defineAsyncComponent

### ISSUE THREAD

**Issue by 7virus7** [Jenesius/vue-modal#118]
**Is your feature request related to a problem? Please describe.**
If the component is connected using defineAsyncComponent, then the animation does not work on the first load

**Describe the solution you'd like**
Add transition-group prop appear or setting for it
```return h(TransitionGroup, {name: configuration.animation, tag: "div"}``` 
to
```return h(TransitionGroup, {name: configuration.animation, tag: "div", appear: true}``` 
or 
```return h(TransitionGroup, {name: configuration.animation, tag: "div", appear: configuration.appear}```

**Comment by Jenesius** [comment]
Please note version **1.11.7**. I added the `appear` value to the config.

``` ts
import {config} from "jenesius-vue-modal"
config({
  appear: true
})
```

I also set it to `true` by default.

**Comment by 7virus7** [comment]
Thank you to!
