### ISSUE TITLE
Background scroll option

### ISSUE THREAD

**Issue by ina6ra** [Jenesius/vue-modal#26]
I want the option to scroll the area below with the modal open.
It was possible with 1.0.14.

**Comment by Jenesius** [comment]
Now, when u open the modal lib add scroll:hidden to body.
U want to manage it?

**Comment by Jenesius** [comment]
@ina6ra ,I add config in version 1.2.2
```
import {config} from "jenesius-vue-modal";
config({
    scrollLock: false
});
```
scrollLock: Boolean, Default - true, When one or more modal was opened and scrollLock = true, page cant be scrolled.
For available scroll set scrollLock to false.

**Comment by Jenesius** [comment]
Done, new version of package downloaded.

**Comment by Jenesius** [comment]
Sorry, 1.2.3 version

**Comment by ina6ra** [comment]
Thank you for the quick reply!
I confirmed that it works 👍

**Comment by Jenesius** [comment]
Glad to help!

**Comment by folamy** [comment]
Hi @Jenesius, please how would I  add config to my project?
