### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by pluxain** [Jenesius/vue-modal#33]
Hello, this is more a question than an issue but could not use a label :)

Do you plan on adding Typescript support adding the types, to enable the usage of your library in a TS project without shutting down TS on every import?
```typescript
// @ts-expect-error no TS types available yet
import { openModal } from 'jenesius-vue-modal'
```
Thanks in anticipate.

**Comment by Jenesius** [comment]
I will mark thiw Issue like Feature
And I will try to add faster. For first time u can wrapper over my function

**Comment by Jenesius** [comment]
Ohh, i was busy
Okay, 
work in progress

**Comment by Jenesius** [comment]
Updated test

**Comment by Jenesius** [comment]
Done!
