### ISSUE TITLE
[ConfigInterface] The definition of backgroundClose is missing in d.ts.

### ISSUE THREAD

**Issue by masatada-kurihara** [Jenesius/vue-modal#42]
https://github.com/Jenesius/vue-modal/blob/main/dist/dts/utils/config.d.ts#L5

In the original Typescript, it looks like this.
https://github.com/Jenesius/vue-modal/blob/22728664e80d736e6f2288954bc07154bd5f2d5e/plugin/utils/config.ts#L7

**Comment by Jenesius** [comment]
@masatada-kurihara 
Hmm, is new version of library
I update version of library to 1.4.6

**Comment by Jenesius** [comment]
New version: 1.4.6
I hope that resolve ur problem 👍

**Comment by masatada-kurihara** [comment]
@Jenesius 
Thanks for the quick response! I was able to confirm that it works well.
