### ISSUE TITLE
Uncaught (in promise) Error: Modal's queue is not empty. Probably some modal reject closing by onClose hook.

### ISSUE THREAD

**Issue by billbravo99** [Jenesius/vue-modal#85]
**Describe the bug**
why i get the error in console
<img width="883" alt="image" src="https://github.com/Jenesius/vue-modal/assets/124110838/ccc704b7-b02c-4062-923c-3f37719d1221">

**Please complete the following information:**
 - Chrome

this is my router:
<img width="883" alt="image" src="https://github.com/Jenesius/vue-modal/assets/124110838/081eb09a-2350-48eb-a761-ede07b81d627">
<img width="883" alt="image" src="https://github.com/Jenesius/vue-modal/assets/124110838/189193eb-48d6-4fa6-9ebc-f8dfeddb86e4">

**Comment by Jenesius** [comment]
Hi, Do you have the work repo where I can test this problem on my pc?

**Comment by Jenesius** [comment]
@billbravo99 , To solve this problem, I need a little more information than is available. Ideally, a repository with this disease. If this option is not possible, specify the version of jenesius-vue-modal and also attach two files router.js and Login.vue.

## About mistakes
This exception (error) is thrown only in one case: if using openModal failed to close previously opened modal windows. If we look at the implementation of this function, we will see the following check:
```ts
if (modalQueue.value.length) throw ModalError.QueueNoEmpty();
```

-----

As a test, I suggest you look at what the value of modalQueue is. Fortunately, you can import it directly:
```ts
import {modalQueue} from "jenesius-vue-modal";

window.test = () => console.log(modalQueue.value)
```

And call it from the browser console.
