### ISSUE TITLE
add side drawer feature

### ISSUE THREAD

**Issue by morteza-mortezai** [Jenesius/vue-modal#88]
Hi,
Is it possible to implement this modal as a side drawer ?
may by adding a new animation to be opened from left or right while it cover half of screen

**Comment by Jenesius** [comment]
@morteza-mortezai ,Hi, can you provide the example.
___

Hmm, now we can change all animation by override css. I not at home now and can't check next solution:
1. Add to Your modal the next css class **.modal-test**
2. Add global css rules: _.modal-container:has(.modal-test) {...}_

This rules must be applied only for this one modal. 

If it's will not work I will find the solution after some hours.

Related link:[css had](https://developer.mozilla.org/en-US/docs/Web/CSS/:has)
Related link: [modal styles](https://modal.jenesius.com/guide/details-styles.html)

**Comment by Jenesius** [comment]
Also, I created the following example:

![rec-tab (8)](https://github.com/Jenesius/vue-modal/assets/21982550/cf0bb816-5d35-42e5-b24d-89baaa9d871d)

You can play around with it by cloning the repository and running `npm run serve`. Then open the resulting server and go to the `Sidebar modal Example`. Also this example is [here](https://github.com/Jenesius/vue-modal/tree/main/examples/side-modal). If that's what suits you - I recommend looking at the `css` described in this folder inside the `vue` component.

If this is not the right or not quite the solution - let's look further!

**Comment by morteza-mortezai** [comment]
that's nice !
