### ISSUE TITLE
Do you need core-js?

### ISSUE THREAD

**Issue by ina6ra** [Jenesius/vue-modal#9]
core-js in package.json,
where are you using it?

**Comment by Jenesius** [comment]
Hello!
By default, when I create a blank project using vue-cli, it adds two deps: core-js and vue.
Core is being a scope of polyfills. I think that we use core-js (or some other vue's library, like vue-service), because after removing core-js form package. json and install **clean** project I find the core-js library in node-modules.


In result, I remove core-js from dependencies. Thanks @ina6ra

**Comment by Jenesius** [comment]
Some modules in npm have next config
![image](https://user-images.githubusercontent.com/21982550/128056795-79e7199f-1375-40de-82ed-fdf76ac1adea.png)

They put vue in peer dependence, but i will save vue in main dependence(i dont think that it will helpfull, what do you think?)

**Comment by ina6ra** [comment]
Confirmed in a new project.

```
$ vue --verion
@vue/cli 4.5.13
$ vue create my-project
> Default (Vue 3) ([Vue 3] babel, eslint)
$ cd my-project
$ npm ls vue
`-- vue@3.1.5
$ npm ls core-js
+-- @vue/cli-plugin-babel@4.5.13
| `-- @vue/babel-preset-app@4.5.13
|   `-- core-js@3.16.0  deduped
`-- core-js@3.16.0
$ yarn add jenesius-vue-modal
$ npm ls vue
+-- jenesius-vue-modal@1.0.9
| `-- vue@3.1.5  deduped
`-- vue@3.1.5
$ npm ls core-js
+-- @vue/cli-plugin-babel@4.5.13
| `-- @vue/babel-preset-app@4.5.13
|   `-- core-js@3.16.0  deduped
`-- core-js@3.16.0
```

In addition to ``core-js``, there were duplicate ``vue`` that I did not use.

Both are not mentioned in ``vue-js-modal``, so I think you can delete both.
https://www.npmjs.com/package/vue-js-modal

Since ``vue-js-modal`` uses ``resize-observer-polyfill``, it is Dependencies,
but ``jenesius-vue-modal`` does not use it, so I don't think you need it either.
https://github.com/euvl/vue-js-modal/search?q=resize-observer-polyfill

**Comment by Jenesius** [comment]
i will today test library without vue-cli
And then write summary

**Comment by Jenesius** [comment]
Hmm, adding hooks take more time...
I read npm's documentation and find that dependencies is a list of package that used in module(For example import {something} from something;), devDep is a modules that using for development: linters, tests or other
I use only vue, so removing core-js is right!
Thnx!

**Comment by ina6ra** [comment]
Thanks @Jenesius
I confirmed that it was supported in version 1.0.14.
