### ISSUE TITLE
Vue.use(Modal) support?

### ISSUE THREAD

**Issue by DucNguyenVan** [Jenesius/vue-modal#90]
Hi, thank you for your great library.
I am switching from vue-js-modal to vue-modal.
In vue-js-modal, I was able to set up like below:
```js
import VModal from 'vue-js-modal'
import { createApp } from 'vue'
const app = createApp(options)
app.use(VModal)
```
How could I import vue-modal in the same way? (without using template `<widget-container-modal />`)
```js
import VModal from 'jenesius-vue-modal'  // like this
import { createApp } from 'vue'
const app = createApp(options)
app.use(VModal)
```

**Comment by Jenesius** [comment]
@DucNguyenVan, Hi! Thank you for your words of gratitude.
Did I understand correctly that you do not have access to the App.vue component and cannot insert a container there:
```vue
<template>
    // Othe code
    <container />
</template>
<script setup>
    import {container} from "jenesius-vue-modal";
</script>
``` 

If this method does not suit you, give me a couple of hours and I will add the ability to use **.use**.

**Comment by DucNguyenVan** [comment]
yes, I do not have access to the App.vue (I dont have App.vue file)

**Comment by Jenesius** [comment]
Okay, You integrate Vue inside your project. Something like [this](https://vuejs.org/guide/extras/ways-of-using-vue.html#standalone-script). I will create a test project for test it.

**Comment by DucNguyenVan** [comment]
@Jenesius 
> Do you have a public repo where I can see how vue-js-modal work with existing html project?
Sorry I don't have a public repo

>  I'm still thinking of a more elegant solution, but the following will also work:

Thank you, I will test it

> Okay, You integrate Vue inside your project. Something like [this](https://vuejs.org/guide/extras/ways-of-using-vue.html#standalone-script).

Yes, I'm using Vue as a Standalone way

**Comment by DucNguyenVan** [comment]
@Jenesius 
I tested this solution, but it did not work.
https://github.com/Jenesius/vue-modal/issues/90#issuecomment-1789303525
Here is the error log.
I found that `app._component.render` was returning undefined. I think it could be the reason that makes your script not work.
```
entry.js:26 Uncaught TypeError: Cannot read properties of undefined (reading 'apply')
    at Proxy.fakeRender
    at renderComponentRoot (runtime-core.esm-bundler.js:1187:1)
```

**Comment by Jenesius** [comment]
@DucNguyenVan Can you send me your main.ts/js file. 
Also you can try just it:
```ts
    const fakeRender = function (...attr) {
      return [ createVNode(container, {}) ]
    }
    app._component.render = fakeRender;
```

**Comment by DucNguyenVan** [comment]
@Jenesius 
Here is my main.js
```.js
import {openModal, container} from "jenesius-vue-modal";
import store from "./store.js";
import { createApp, createVNode } from 'vue/dist/vue.esm-bundler.js'
import MyModal from "./MyModal";

const createCommonApp = (options) => {
  const app = createApp(options)
  app.use(store)
  app.use({
    install(app) {
      const fakeRender = function (...attr) {
        return [ createVNode(container, {}) ]
      }
      app._component.render = fakeRender;
    }
  })
  return app
}


document.addEventListener("DOMContentLoaded", () => {
  createCommonApp({
    components: {
      MyModal
    },
    methods: {
      openDetailModal(){
        openModal(MyModal);
      }
    },
  })
  .mount('#app')
});
```

> Also you can try just it:
    const fakeRender = function (...attr) {
      return [ createVNode(container, {}) ]
    }
    app._component.render = fakeRender;

And I tried it, but after `app._component.render = fakeRender;`, it replaced my entire HTML content.

**Comment by DucNguyenVan** [comment]
@Jenesius 
I found a way to make it work as a quick hot-fix.
In the HTML file, I add `<widget-container-modal />` to the last line (so it will not replace existing HTML contents), and it works as expected!

index.html
```html
<div id="app">
   # other html contents
   <widget-container-modal />
</div>
```

main.js
```js
import {openModal, container} from "jenesius-vue-modal";
import store from "./store.js";
import { createApp, createVNode } from 'vue/dist/vue.esm-bundler.js'
import MyModal from "./MyModal";

const createCommonApp = (options) => {
  const app = createApp(options)
  app.use(store)
  return app
}


document.addEventListener("DOMContentLoaded", () => {
  createCommonApp({
    components: {
      MyModal,
      WidgetContainerModal: container
    },
    methods: {
      openDetailModal(){
        openModal(MyModal);
      }
    },
  })
  .mount('#app')
});

```

**Comment by Jenesius** [comment]
@DucNguyenVan 
This solution already somewhat resembles a standard one. Can you describe how you use Vue in your project?
I would like to document this problem and can suggest a more elegant solution (via using .use). How you build your project.

**Comment by DucNguyenVan** [comment]
@Jenesius 
My project uses Rails, webpack, and Vue 3.
Vue 3 was used as a standalone way, like this: https://github.com/Jenesius/vue-modal/issues/90#issuecomment-1792118041.

Project structure is almost like this:
https://alfianeffendy.medium.com/setup-single-page-application-in-rails-with-vue-3-and-typescript-vue-cli-7bb498069d16.

**Comment by anshirko** [comment]
@DucNguyenVan
Very interesting link. I tried to familiarize myself with how `Vue` is built into the application in this case. Of course, it would be simpler in the case of an open repository, however, due to the fact that a large number of technologies are used, this can be quite expensive.

In the case of `vue-js-modal`, a separate instance of `Vue` is created, but for the Vue3 version this will not work. The exact location of the container must be specified. However, I need to experiment with `.use` and I’m thinking of adding it to the functionality of this library.

In your case, the example given is an absolutely correct solution to this problem. Very similar to creating a [global component](https://v3.ru.vuejs.org/ru/guide/component-registration.html).
Thus, your solution is the simplest and most correct, another solution:
```ts
import {container} from "jenesius-vue-modal"
const app = createApp(options)
app.use(store)
app.component('widget-container-modal', container)
return app
```
And then also add it to `html`. But your method is shorter.

-------

@jenesius , Did You found something?
