### ISSUE TITLE
Create multiple instances

### ISSUE THREAD

**Issue by saleh-gholamian** [Jenesius/vue-modal#91]
Please add this feature to be able to have multiple ModalContainer instances, or rather to have multiple ModalContainer, there are various scenarios where we need to be able to display modals in separate containers, unfortunately none of the existing libraries have such a feature.

**Comment by Jenesius** [comment]
Hello! Interesting offer. I need to think through the concept and implement some basic implementation.
I also need to think about how modal windows in different containers will be displayed.

Thanks for the idea! In this issue I will add the implementation progress.

Or maybe divide it all into a namespace, where each container displays its own.

**Comment by Jenesius** [comment]
This task will be discussed here. [Discussion](https://github.com/Jenesius/vue-modal/discussions/94)

**Comment by Jenesius** [comment]
@saleh-gholamian 
Hello! I did a little development to implement `namespace`. At the moment it is at the finished draft stage. All functionality has been implemented, but I continue to test and optimize the current code.

To see the result, you need to:
1. Clone the current repository
2. Go to the `issue_94` branch
3. `npm ci`
4. `npm run serve`
5. Go to `http://localhost:8080/namespace`

This example is described in [here](https://github.com/Jenesius/vue-modal/tree/issue_94/examples/use-namespace).

**Comment by Jenesius** [comment]
- Docs done. https://modal.jenesius.com/guide/namespace.html
- Tests done.

Now everything inside `main` branch. I think I will update version tomorrow to `1.10.0`.
I want to test better because there are big changes involved.

**Comment by anshirko** [comment]
I start update docs for new options: guide-methods.md. Also, add new information about getCurrentModal

**Comment by Jenesius** [comment]
@saleh-gholamian 
Version: **1.10.0**
Docs [here](https://modal.jenesius.com/guide/namespace.html).
