### ISSUE TITLE
Open Modal Vue 3

### ISSUE THREAD

**Issue by anshirko** [Jenesius/vue-modal#95]
Does this library support vue 2?

**Comment by Jenesius** [comment]
Привет. Нет.
Данная библиотека полагается на механизм `reactive/ref`, которые полностью отсутствуют в `Vue 2`.

**Comment by bmulholland** [comment]
Vue 2.7 has those, doesn’t it?

**Comment by Jenesius** [comment]
@bmulholland Hmm, I'll test this

**Comment by bmulholland** [comment]
I may also try it out in the coming days and report back :)

**Comment by bmulholland** [comment]
On a first pass, no I couldn't get it working in Vue 2.7
